### ISSUE TITLE
Unknown caller instead of number

### ISSUE THREAD

**Issue by msvitek** [QualityUnit/LivePhone-iOS#2]
Similar as https://github.com/QualityUnit/LivePhone-Android/issues/1, however in iOS the notification displays `Unknown` caller and after the call is picked up it actually displays the caller's phone number

Screenshot declines the call, but the notification displays Unknown like this:
![obrázok](https://user-images.githubusercontent.com/10156080/70518179-346f8b80-1b3a-11ea-8646-9ad5d73593f8.png)

After the call is picked up it displays the number:
![obrázok](https://user-images.githubusercontent.com/10156080/70518297-6aad0b00-1b3a-11ea-8b1a-25c655e74013.png)

**Comment by jstofira** [comment]
@rkostrab there is increasing demand from customers on various missing features in the LivePhone app.
One of the main missing features is to be able to see the caller's name, not just the number. 
Will be possible to prioritize this?

**Comment by rkostrab** [comment]
showing number or name if it's possible instead "Unknown" caller will be fixed in 1.5.11
